import turtle

def draw_initials():
    window=turtle.Screen()
    window.bgcolor("red")
    ini=turtle.Turtle()
    ini.shape("arrow")
    ini.color("yellow")
    ini.backward(50)
    ini.left(90)
    ini.backward(50)
    ini.right(90)
    ini.forward(50)
    ini.right(90)
    ini.forward(50)
    ini.left(90)
    ini.backward(50)
    ini.penup()
    ini.forward(100)
    ini.right(110)
    ini.pendown()
    ini.backward(105)
    ini.penup()
    ini.right(70)
    ini.forward(70)
    ini.left(110)
    ini.pendown()
    ini.forward(105)

draw_initials()
